-- ----------------------------- 2026-03-31 add by liheng1122--------------begin

-- 建表语句

CREATE TABLE IF NOT EXISTS `T_LIMS_SCHEDULE_TASK_LOG`(
     `ID` BIGINT NOT NULL COMMENT '主键',
     `CONFIGID` VARCHAR(32)  DEFAULT NULL COMMENT '定时器任务主键',
     `PARAM` VARCHAR(96)  DEFAULT NULL COMMENT '方法所需的参数（可以为空）',
     `CRON` VARCHAR(96)  DEFAULT NULL COMMENT 'CRON表达式',
     `STARTTIME` DATETIME DEFAULT NULL COMMENT '开始时间',
     `ENDTIME` DATETIME DEFAULT NULL COMMENT '结束时间',
     `SUCCESS` VARCHAR(36)  DEFAULT NULL COMMENT '是否执行成功（0-否 1-是）',
     `EXECUTEDRESULT` VARCHAR(300)  DEFAULT NULL COMMENT '任务执行的业务结果',
     `CREATEDBYID` VARCHAR(36)  DEFAULT NULL COMMENT '制单人编码',
     `CREATEDBYNAME` VARCHAR(60)  DEFAULT NULL COMMENT '制单人名称',
     `CREATEDTIME` DATETIME DEFAULT NULL COMMENT '制单时间',
     `CREATEDBYORGID` VARCHAR(36)  DEFAULT NULL COMMENT '制单人单位编码',
     `CREATEDBYORGNAME` VARCHAR(270)  DEFAULT NULL COMMENT '制单人单位名称',
      PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='岗位交班';

-- 旧版审计跟踪，跟踪配置变更语句

INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','ID','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CONFIGID','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','PARAM','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CRON','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','STARTTIME','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','ENDTIME','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','SUCCESS','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','EXECUTEDRESULT','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYID','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYNAME','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDTIME','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGID','1','liheng1122','liheng1122', NOW());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGNAME','1','liheng1122','liheng1122', NOW());
COMMIT;

INSERT INTO T_CORE_AT_CONFIG (ID, AUDITTRAIL, CREATEDBYID, CREATEDBYNAME, CREATEDTIME)
VALUES ('T_LIMS_SCHEDULE_TASK_LOG', '1', 'liheng1122', 'liheng1122', NOW());

-- 审计跟踪V2，跟踪配置变更语句

INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','ID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CONFIGID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','PARAM','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CRON','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','STARTTIME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','ENDTIME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','SUCCESS','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','EXECUTEDRESULT','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYNAME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDTIME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,`COLUMN`,AUDITABLE) VALUES (F_GET_SEQ_CORE(),'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGNAME','1');
COMMIT;

INSERT INTO T_CORE_AUDIT_CONFIG (ID, NAME, CATEGORY, AUDITABLE)
VALUES ('T_LIMS_SCHEDULE_TASK_LOG', '岗位交班', 'service', '1');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.SERVICE_NAME', '岗位交班', '岗位交班', 'zh-CN', '岗位交班');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.ID', '岗位交班的主键', '主键', 'zh-CN', '主键');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.CONFIGID', '岗位交班的定时器任务主键', '定时器任务主键', 'zh-CN', '定时器任务主键');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.PARAM', '岗位交班的方法所需的参数（可以为空）', '方法所需的参数（可以为空）', 'zh-CN', '方法所需的参数（可以为空）');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.CRON', '岗位交班的CRON表达式', 'CRON表达式', 'zh-CN', 'CRON表达式');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.STARTTIME', '岗位交班的开始时间', '开始时间', 'zh-CN', '开始时间');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.ENDTIME', '岗位交班的结束时间', '结束时间', 'zh-CN', '结束时间');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.SUCCESS', '岗位交班的是否执行成功（0-否 1-是）', '是否执行成功（0-否 1-是）', 'zh-CN', '是否执行成功（0-否 1-是）');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.EXECUTEDRESULT', '岗位交班的任务执行的业务结果', '任务执行的业务结果', 'zh-CN', '任务执行的业务结果');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYID', '岗位交班的制单人编码', '制单人编码', 'zh-CN', '制单人编码');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYNAME', '岗位交班的制单人名称', '制单人名称', 'zh-CN', '制单人名称');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.CREATEDTIME', '岗位交班的制单时间', '制单时间', 'zh-CN', '制单时间');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYORGID', '岗位交班的制单人单位编码', '制单人单位编码', 'zh-CN', '制单人单位编码');
CALL INSERTI18N('T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYORGNAME', '岗位交班的制单人单位名称', '制单人单位名称', 'zh-CN', '制单人单位名称');
CALL INSERTI18N('LIMS.MODULE.SP.FOLDERS.MODAL.ADD', '新增', '新增', 'zh-CN', '新增');
CALL INSERTI18N('LIMS.MODULE.SP.FOLDERS.TAB.BASE_INFO', '基本信息', '基本信息', 'zh-CN', '基本信息');
CALL INSERTI18N('LIMS.MODULE.SP.FOLDERS.BUTTON.BUTTON', '按钮', '按钮', 'zh-CN', '按钮');
CALL INSERTI18N('LIMS.MODULE.SP.FOLDERS.TIP.TIP', '提示框', '提示框', 'zh-CN', '提示框');
CALL INSERTI18N('LIMS.MODULE.SP.FOLDERS.MODAL.MODAL', '对话框', '对话框', 'zh-CN', '对话框');


-- 创建菜单语句
INSERT INTO T_CORE_MENU (ID, MENUNAME, HREF, PARENTID, ORDERNO, ICON, MENUINITNAME)
VALUES ('11', '11', '/secure/lims/module/sp/schedule-task-logs/page/edit-list', '11', '11', 'null', '11');
INSERT INTO T_CORE_MENU (ID, MENUNAME, HREF, PARENTID, ORDERNO, ICON, MENUINITNAME)
VALUES ('03', '11查询', '/secure/lims/module/sp/schedule-task-logs/page/search-list', '11', '03', 'null', '11查询');

INSERT INTO T_CORE_TABLE (ID, AUDITABLE, ATTACHMENT)
VALUES ('T_LIMS_SCHEDULE_TASK_LOG', '0', '0');


COMMIT;

-- ----------------------------- 2026-03-31 add by liheng1122------------end