-- ----------------------------- 2026-03-31 add by liheng1122--------------begin

-- 建表语句
CREATE TABlE DBO.T_LIMS_SCHEDULE_TASK_LOG(
    ID BIGINT NOT NULL,
    CONFIGID VARCHAR(32)  NULL ,
    PARAM VARCHAR(96)  NULL ,
    CRON VARCHAR(96)  NULL ,
    STARTTIME DATETIME NULL ,
    ENDTIME DATETIME NULL ,
    SUCCESS VARCHAR(36)  NULL ,
    EXECUTEDRESULT VARCHAR(300)  NULL ,
    CREATEDBYID VARCHAR(36)  NULL ,
    CREATEDBYNAME VARCHAR(60)  NULL ,
    CREATEDTIME DATETIME NULL ,
    CREATEDBYORGID VARCHAR(36)  NULL ,
    CREATEDBYORGNAME VARCHAR(270)  NULL ,
    CONSTRAINT PK_LIMS_SCHEDULE_TASK_LOG PRIMARY KEY(ID));
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'岗位交班' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'主键' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'ID';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'定时器任务主键' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'CONFIGID';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'方法所需的参数（可以为空）' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'PARAM';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CRON表达式' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'CRON';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'开始时间' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'STARTTIME';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'结束时间' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'ENDTIME';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否执行成功（0-否 1-是）' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'SUCCESS';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'任务执行的业务结果' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'EXECUTEDRESULT';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'制单人编码' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'CREATEDBYID';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'制单人名称' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'CREATEDBYNAME';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'制单时间' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'CREATEDTIME';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'制单人单位编码' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'CREATEDBYORGID';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'制单人单位名称' , @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_LIMS_SCHEDULE_TASK_LOG', @level2type=N'COLUMN',@level2name=N'CREATEDBYORGNAME';

-- 旧版审计跟踪，跟踪配置变更语句

INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','ID','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CONFIGID','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','PARAM','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CRON','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','STARTTIME','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','ENDTIME','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','SUCCESS','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','EXECUTEDRESULT','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYID','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYNAME','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDTIME','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGID','1','liheng1122','liheng1122', GETDATE());
INSERT INTO T_CORE_AT_CONFIG_LINE (ID,CONFIGID,COLUMNID,AUDITTRAIL,CREATEDBYID,CREATEDBYNAME,CREATEDTIME) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGNAME','1','liheng1122','liheng1122', GETDATE());

INSERT INTO T_CORE_AT_CONFIG (ID, AUDITTRAIL, CREATEDBYID, CREATEDBYNAME, CREATEDTIME)
VALUES ('T_LIMS_SCHEDULE_TASK_LOG', '1', 'liheng1122', 'liheng1122', GETDATE());

-- 审计跟踪V2，跟踪配置变更语句

INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','ID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CONFIGID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','PARAM','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CRON','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','STARTTIME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','ENDTIME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','SUCCESS','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','EXECUTEDRESULT','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYNAME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDTIME','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGID','1');
INSERT INTO T_CORE_AUDIT_CONFIG_COLUMN (ID,CONFIGID,"COLUMN",AUDITABLE) VALUES (NEXT VALUE FOR SEQ_CORE,'T_LIMS_SCHEDULE_TASK_LOG','CREATEDBYORGNAME','1');

INSERT INTO T_CORE_AUDIT_CONFIG (ID, NAME, CATEGORY, AUDITABLE)
VALUES ('T_LIMS_SCHEDULE_TASK_LOG', '岗位交班', 'service', '1');
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.SERVICE_NAME', N'岗位交班', N'岗位交班', N'zh-CN',N'岗位交班';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.ID', N'岗位交班的主键', N'主键', N'zh-CN',N'主键';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.CONFIGID', N'岗位交班的定时器任务主键', N'定时器任务主键', N'zh-CN',N'定时器任务主键';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.PARAM', N'岗位交班的方法所需的参数（可以为空）', N'方法所需的参数（可以为空）', N'zh-CN',N'方法所需的参数（可以为空）';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.CRON', N'岗位交班的CRON表达式', N'CRON表达式', N'zh-CN',N'CRON表达式';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.STARTTIME', N'岗位交班的开始时间', N'开始时间', N'zh-CN',N'开始时间';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.ENDTIME', N'岗位交班的结束时间', N'结束时间', N'zh-CN',N'结束时间';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.SUCCESS', N'岗位交班的是否执行成功（0-否 1-是）', N'是否执行成功（0-否 1-是）', N'zh-CN',N'是否执行成功（0-否 1-是）';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.EXECUTEDRESULT', N'岗位交班的任务执行的业务结果', N'任务执行的业务结果', N'zh-CN',N'任务执行的业务结果';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYID', N'岗位交班的制单人编码', N'制单人编码', N'zh-CN',N'制单人编码';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYNAME', N'岗位交班的制单人名称', N'制单人名称', N'zh-CN',N'制单人名称';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.CREATEDTIME', N'岗位交班的制单时间', N'制单时间', N'zh-CN',N'制单时间';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYORGID', N'岗位交班的制单人单位编码', N'制单人单位编码', N'zh-CN',N'制单人单位编码';
EXEC  DBO.INSERTI18N  N'T_LIMS_SCHEDULE_TASK_LOG.CREATEDBYORGNAME', N'岗位交班的制单人单位名称', N'制单人单位名称', N'zh-CN',N'制单人单位名称';
EXEC  DBO.INSERTI18N  N'LIMS.MODULE.SP.FOLDERS.MODAL.ADD', N'新增', N'新增', N'zh-CN',N'新增';
EXEC  DBO.INSERTI18N  N'LIMS.MODULE.SP.FOLDERS.TAB.BASE_INFO', N'基本信息', N'基本信息', N'zh-CN',N'基本信息';
EXEC  DBO.INSERTI18N  N'LIMS.MODULE.SP.FOLDERS.BUTTON.BUTTON', N'按钮', N'按钮', N'zh-CN',N'按钮';
EXEC  DBO.INSERTI18N  N'LIMS.MODULE.SP.FOLDERS.TIP.TIP', N'提示框', N'提示框', N'zh-CN',N'提示框';
EXEC  DBO.INSERTI18N  N'LIMS.MODULE.SP.FOLDERS.MODAL.MODAL', N'对话框', N'对话框', N'zh-CN',N'对话框';

-- 创建菜单语句
INSERT INTO T_CORE_MENU (ID, MENUNAME, HREF, PARENTID, ORDERNO, ICON, MENUINITNAME)
VALUES ('11', '11', '/secure/lims/module/sp/schedule-task-logs/page/edit-list', '11', '11', 'null', '11');
INSERT INTO T_CORE_MENU (ID, MENUNAME, HREF, PARENTID, ORDERNO, ICON, MENUINITNAME)
VALUES ('03', '11查询', '/secure/lims/module/sp/schedule-task-logs/page/search-list', '11', '03', 'null', '11查询');

INSERT INTO T_CORE_TABLE (ID, AUDITABLE, ATTACHMENT)
VALUES ('T_LIMS_SCHEDULE_TASK_LOG', '0', '0');


-- ----------------------------- 2026-03-31 add by liheng1122------------end